server:
  port: 10002
spring:
  application:
    name: xh-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins:
              - "http://localhost:8000"
              - "http://localhost:8080"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
            # 允许response的head信息
            # 默认仅允许如下6个：
            #     Cache-Control
            #     Content-Language
            #     Content-Type
            #     Expires
            #     Last-Modified
            #     Pragma
            #exposed-headers:
      routes:
        - id: xh-admin # 路由id
          uri: lb://xh-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: xh-service # 路由id
          uri: lb://xh-service
          predicates:
            - Path=/api/service/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


#oauth2-server-url: http://localhost:10100/uac
#security:
#  oauth2: #与oauth2-server对应的配置
#    client:
#      client-id: admin
#      client-secret: 123456
#      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
#      access-token-uri: ${oauth2-server-url}/oauth/token
#    resource:
#      jwt:
#        key-uri: ${oauth2-server-url}/oauth/token_key
#logging:
#  level:
#   - debug